(in-package :hawksbill.golbin.frontend)

(setf *categories*
      '(("Sports"
         ("American Football" nil)
         ("Badminton" t)
         ("Baseball" nil)
         ("Basketball" nil)
         ("Boxing" nil)
         ("Cricket" t)
         ("Cycling" nil)
         ("Hockey" t)
         ("Golf" t)
         ("Handball" nil)
         ("Olympics" nil)
         ("Racing" nil)
         ("Rugby" nil)
         ("Table Tennis" nil)
         ("Tennis" nil))
        ("Entenrtainment"
         ("Arts" t)
         ("Books" t)
         ("Celebrities" t)
         ("Movies" t)
         ("Music" t)
         ("TV" t)
         ("Humor" t))
        ("Lifestyle"
         ("Automotive" t)
         ("Culture" t)
         ("Food and Beverage" t)
         ("Home and Garden" t)
         ("Theatre" t)
         ("Travel" t)
         ("Health" t))
        ("Technology"
         ("Computing" t)
         ("Internet" t)
         ("Personal Technology" t)
         ("Video Games" t))
        ("Business"
         ("Companies" t)
         ("Economy" t)
         ("Industry" t)
         ("Markets" t))
        ("Education")
        ("Science"
         ("Environmenent" t)
         ("Geography" t)
         ("Space" t))
        ("Headlines")
        ("Politics")
        ("Religion")))
