(in-package :hawksbill.golbin.frontend)

(defun on-load ()
  (import-macros-from-lisp '$$)
  (ps ($$ (document ready)
        (let ((that nil)
              (subnav nil)
              (in-nav nil)))
        (flet ((display-subcategory ()
                 (unless in-nav
                   (setf subnav ((@ ($ "#subnav") children)))
                   ((@ ($ "#subnav") empty))
                   ((@ ($ "#subnav") append) ((@ ((@ ($ this) children) "ul") children)))
                   (setf in-nav t)
                   (setf that this))
                 nil)
               (hide-subcategory ()
                 (when in-nav
                   ((@ ((@ ($ that) children) "ul") append) ((@ ($ "#subnav") children)))
                   ((@ ($ "#subnav") append) subnav)
                   (setf in-nav nil))
                 nil)))
        ((@ ($ "#prinav .cat") hover) display-subcategory (lambda () ()))
        ((@ ($ "#nav") hover) (lambda () ()) hide-subcategory)
        nil)))
