(in-package :hawksbill.golbin.frontend)

(defun on-load ()
  (import-macros-from-lisp '$$)
  (ps ($$ (document ready)
        (flet ((display-subcategory ()
                 ((@ ($ "#subnav") append) ((@ ((@ ($ this) children) "ul") children)))
                 nil)
               (hide-subcategory ()
                 ((@ ((@ ($ this) children) "ul") append) ((@ ($ "#subnav") children)))
                 nil)))
        ((@ ($ "#nav .cat") hover) display-subcategory hide-subcategory)
        nil)))
