(in-package :hawksbill.golbin)

(setf *dimensions* '("envt" "lang"))
(setf *valid-envts* '("dev" "prod"))
(setf *valid-langs* '("en-IN" "hi-IN" "mr-IN"))
(setf *config*
      `(("master" ("site" ("name" "Golbin")
                          ("url" "golb.in")
                          ("lang" "en-IN"))
                  ("hunchentoot" ("debug" ("errors" ("catch" nil)
                                                    ("show" nil))
                                          ("backtraces" nil)))
                  ("path" ("uploads" ,(merge-pathnames "../data/uploads/" *home*))
                          ("photos" ,(merge-pathnames "../data/static/photos/" *home*))
                          ("locale" ,(merge-pathnames "locale/" *home*)))
                  ("photo" ("article-lead" ("side" ("max-width" 300)
                                                   ("max-height" 300))
                                           ("block" ("max-width" 600)
                                                    ("max-height" 300))
                                           ("index-thumb" ("max-width" 65)
                                                          ("max-height" 65))
                                           ("related-thumb" ("max-width" 100)
                                                            ("max-height" 100)))
                           ("author" ("avatar" ("max-width" 100)
                                               ("max-height" 100))
                                     ("article-logo" ("max-width" 50)
                                                     ("max-height" 50))))
                  ("pagination" ("article" ("limit" 10) ; number of articles per (index) page
                                           ("range" 10) ; number of entries in pagination markup
                                           ("related" 4)
                                           ("editorial" ("lead-photo-select-pane" 16)))
                                ("home" ("carousel" ("tabs" 5))))
                  ("parenscript" ("obfuscation" nil)))
        ("envt:dev" ("db" ("type" "prevalence"))
                    ("fe" ("restas" ("package" :hawksbill.golbin.frontend)
                                    ("port" 8000)))
                    ("ed" ("restas" ("package" :hawksbill.golbin.editorial)
                                    ("port" 8080)))
                    ("hunchentoot" ("debug" ("errors" ("catch" t)
                                                      ("show" t))
                                            ("backtraces" t))))
        ("envt:prod" ("parenscript" ("obfuscation" t)))
        ("lang:en-IN" ("categorys" (("Business"
                                     "Companies"
                                     "Economy"
                                     "Industry"
                                     "Markets")
                                    )))
        ("envt:dev,lang:en-IN" ("db" ("path" ,(merge-pathnames "../data/db/dev/en-IN" *home*))))))
