(in-package :hawksbill.golbin)

(mount-submodule -static- (#:restas.directory-publisher)
  (restas.directory-publisher:*baseurl* '("static"))
  (restas.directory-publisher:*directory* (merge-pathnames "frontend/static/" *home*)))

(define-route route-home ("/") (view-home))
(define-route route-home-page ("/:page/" :parse-vars (list :page #'parse-integer)) (view-home page))
(define-route route-cat ("c/:cat/") (view-cat cat))
(define-route route-cat-page ("c/:cat/:page/" :parse-vars (list :page #'parse-integer)) (view-cat cat page))
(define-route route-cat-subcat ("c/:cat/:subcat/") (view-cat-subcat cat subcat))
(define-route route-cat-subcat-page ("c/:cat/:subcat/:page/" :parse-vars (list :page #'parse-integer)) (view-cat-subcat cat subcat page))
(define-route route-tag ("t/:tag/") (view-tag tag))
(define-route route-tag-page ("t/:tag/:page/" :parse-vars (list :page #'parse-integer)) (view-tag tag page))
(define-route route-author ("a/:author/") (view-author author))
(define-route route-author-page ("a/:author/:page/" :parse-vars (list :page #'parse-integer)) (view-author author page))
(define-route route-article (":(slug-and-id).html") (view-article slug-and-id))
(define-route route-search ("search/") (view-search))
